### ISSUE TITLE
<textarea> and <pre> are not aligned when a width is set

### ISSUE THREAD

**Issue by francesca-cicileo** [kazzkiq/CodeFlask.js#34]
Testcase: http://codepen.io/fcicileo/pen/LWrGwE

![image](https://cloud.githubusercontent.com/assets/12498986/24272638/8a8d98bc-0ff4-11e7-8d75-a659a8cb8063.png)

It appears that when the container has a specific width set via CSS, the code in the `<textarea>` and the `<pre>` is not aligned anymore.

**Comment by d4hines** [comment]
I've noticed this too. Can anyone recommend short term fix?

**Comment by kazzkiq** [comment]
@d4hines These properties seem to quick-fix the issue:

```css
.CodeFlask__textarea {
  white-space: nowrap;
  overflow-x: hidden;
}
```

While this CSS helps, the solution will be implementing horizontal scrolling support for CodeFlask. As of today, it only support vertical scrolling it seems.

**Comment by d4hines** [comment]
Thanks for the response! I tried implementing the above CSS, but didn't notice any difference in the issue.

**Comment by kazzkiq** [comment]
@d4hines That must be overriding by another rule. Adding `.CodeFlask` to the selector should help override it:

```css
.CodeFlask .CodeFlask__textarea {
  white-space: nowrap;
  overflow-x: hidden;
}
```

**Comment by d4hines** [comment]
Hi Kazzkiq,
I tried adding the code you suggested, but am still getting weird formatting issues. If you have the time, could you look at this JsFiddle I've created and tell me what I'm doing wrong: https://jsfiddle.net/d4hines/bb02ykx7/
Thanks!

**Comment by kazzkiq** [comment]
@d4hines It seems to be a issue with the CSS. The selector is applying same properties to both `<pre>` and `<code>`, where `<code>` shouldn't receive those.

The main issue seems to be with `<code>` also receiving `position: absolute`. Removing that property for this element seems to fix the issue, **[as you can see here](https://jsfiddle.net/byw90y7v/)**.

So basically a quick-fix should be adding this to your CSS in order to override the property from CodeFlask:

```css
.CodeFlask .CodeFlask__code {
  position: relative;
}
```
